name: aquilign
channels:
  - defaults
  - conda-forge
  - pytorch
  - rapidsai
  - nvidia
dependencies:
  - python>=3.9
  - pip>=22.0
  - certifi>=2024.2.2
  - charset-normalizer>=3.3.2
  - faiss-gpu>=1.7.4
  - filelock>=3.13.1
  - fsspec>=2024.2.0
  - huggingface_hub=0.23.2
  - idna>=3.6
  - Jinja2>=3.1.3
  - joblib>=1.3.2
  - langdetect>=1.0.9
  - llvmlite>=0.42.0
  - lxml>=5.1.0
  - MarkupSafe>=2.1.5
  - mpmath>=1.3.0
  - networkx>=3.2.1
  - numba>=0.59.0
  - numpy>=1.26.4
  - packaging>=23.2
  - pillow>=10.2.0
  - PyYAML>=6.0.1
  - regex>=2023.12.25
  - requests>=2.31.0
  - safetensors>=0.4.2
  - scikit-learn>=1.4.1.post1
  - scipy>=1.12.0
  - sentence-transformers>=2.5.1
  - six>=1.16.0
  - sympy>=1.12
  - threadpoolctl>=3.3.0
  - tokenizers>=0.15.2
  - tqdm>=4.66.2
  - transformers>=4.38.2
  - typing_extensions>=4.10.0
  - urllib3>=2.2.1
  
