name: aquilign
channels:
  - defaults
  - conda-forge
  - pytorch
  - rapidsai
  - nvidia
dependencies:
  - python>=3.9
  - certifi>=2024.2.2
  - charset-normalizer>=3.3.2
  - faiss-gpu>=1.7.4
  - filelock>=3.13.1
  - fsspec>=2024.2.0
  - huggingface_hub>=0.21.4
  - idna>=3.6
  - Jinja2>=3.1.3
  - joblib>=1.3.2
  - langdetect>=1.0.9
  - llvmlite>=0.42.0
  - lxml>=5.1.0
  - MarkupSafe>=2.1.5
  - mpmath>=1.3.0
  - networkx>=3.2.1
  - numba>=0.59.0
  - numpy>=1.26.4
  - packaging>=23.2
  - pillow>=10.2.0
  - PyYAML>=6.0.1
  - regex>=2023.12.25
  - requests>=2.31.0
  - safetensors>=0.4.2
  - scikit-learn>=1.4.1.post1
  - scipy>=1.12.0
  - sentence-transformers>=2.5.1
  - six>=1.16.0
  - sympy>=1.12
  - threadpoolctl>=3.3.0
  - tokenizers>=0.15.2
  - tqdm>=4.66.2
  - transformers>=4.38.2
  - typing_extensions>=4.10.0
  - urllib3>=2.2.1
  - pip:
    - numpyencoder>=0.3.0
    - nvidia-cublas-cu11>=11.10.3.66
    - nvidia-cublas-cu12>=12.1.3.1
    - nvidia-cuda-cupti-cu12>=12.1.105
    - nvidia-cuda-nvrtc-cu11>=11.7.99
    - nvidia-cuda-nvrtc-cu12>=12.1.105
    - nvidia-cuda-runtime-cu11>=11.7.99
    - nvidia-cuda-runtime-cu12>=12.1.105
    - nvidia-cudnn-cu11>=8.5.0.96
    - nvidia-cudnn-cu12>=8.9.2.26
    - nvidia-cufft-cu12>=11.0.2.54
    - nvidia-curand-cu12>=10.3.2.106
    - nvidia-cusolver-cu12>=11.4.5.107
    - nvidia-cusparse-cu12>=12.1.0.106
    - nvidia-nccl-cu12>=2.19.3
    - nvidia-nvjitlink-cu12>=12.4.99
    - nvidia-nvtx-cu12>=12.1.105
    - torch>=1.13.0
    - triton>=2.2.0

